//! Cross-host tree-diff golden conformance (Phase 557 tail).
//!
//! Loads the shared `wire-format-fixtures/diff/goldens.json` — (before, after) →
//! canonical `TreeOp` op-script pairs whose scripts were generated by running the
//! actual shipped producers (go `diff/diff.go`, rs `src/diff`, py
//! `fuaran_py.ops.diff`). Two sections: `goldens` are pairs where go, rs and py
//! produce the IDENTICAL script — this Rust host asserts `diff == ops` AND
//! `apply(ops, before) == after`. `divergent` pairs carry a per-host expected
//! script under `hosts` (the producers differ in granularity, never correctness);
//! the Rust host asserts against `hosts["rs"]`. Skips cleanly on a standalone
//! checkout where the corpus is absent.

use std::path::PathBuf;

use fuaran_rs::canonical::{JVal, parse, render_canonical};
use fuaran_rs::diff::diff;
use fuaran_rs::ops::apply;
use fuaran_rs::wire::{Node, decode_node, decode_op, encode_node, encode_op};

fn find_goldens() -> Option<PathBuf> {
    let mut dir: PathBuf = env!("CARGO_MANIFEST_DIR").into();
    loop {
        let g = dir
            .join("wire-format-fixtures")
            .join("diff")
            .join("goldens.json");
        if g.is_file() {
            return Some(g);
        }
        if !dir.pop() {
            return None;
        }
    }
}

fn load() -> Option<JVal> {
    let path = find_goldens()?;
    let raw = std::fs::read_to_string(&path).expect("reading diff/goldens.json");
    Some(parse(&raw).expect("diff/goldens.json parses with the host's own JSON layer"))
}

fn arr<'a>(j: &'a JVal, key: &str) -> &'a Vec<JVal> {
    match j.field(key) {
        Some(JVal::Arr(a)) => a,
        other => panic!("expected array field '{key}', got {other:?}"),
    }
}

fn str_field(j: &JVal, key: &str) -> String {
    match j.field(key) {
        Some(JVal::Str(s)) => s.clone(),
        other => panic!("expected string field '{key}', got {other:?}"),
    }
}

// Harness-local upgrade shim: the shared diff-golden family predates the
// 0.2.0 rename law (scalar `value`, collection `source`) and still spells
// `Metric.source`, which the 0.2.0 codec hard-rejects by design. The diff
// comparisons decode → re-encode on both sides, so renaming the key before
// decode keeps the certification live against the family's semantics without
// weakening the codec. Remove when the goldens regenerate on 0.2.0 bytes.
fn upgrade_pre_020(j: &JVal) -> JVal {
    match j {
        JVal::Obj(fields) => {
            let is_scalar_kind = matches!(
                fields.iter().find(|(k, _)| k == "$type"),
                Some((_, JVal::Str(t))) if t == "Metric" || t == "LabelValueRow"
            );
            JVal::Obj(
                fields
                    .iter()
                    .map(|(k, v)| {
                        let k = if is_scalar_kind && k == "source" {
                            "value".to_string()
                        } else {
                            k.clone()
                        };
                        (k, upgrade_pre_020(v))
                    })
                    .collect(),
            )
        }
        JVal::Arr(items) => JVal::Arr(items.iter().map(upgrade_pre_020).collect()),
        other => other.clone(),
    }
}

// A golden before/after sub-object → a decoded Node (render its JVal back to
// canonical JSON, then run the host decoder — the same codec the corpus commits).
fn node_of(j: &JVal, what: &str) -> Node {
    decode_node(&render_canonical(&upgrade_pre_020(j)))
        .unwrap_or_else(|e| panic!("decoding {what}: {e:?}"))
}

// A golden op-script JVal array → its canonical op bytes (decode each op then
// re-encode, so the comparison is against the true canonical form).
fn golden_op_bytes(j: &JVal, what: &str) -> Vec<String> {
    match j {
        JVal::Arr(items) => items
            .iter()
            .enumerate()
            .map(|(i, o)| {
                let op = decode_op(&render_canonical(&upgrade_pre_020(o)))
                    .unwrap_or_else(|e| panic!("decoding {what} op #{i}: {e:?}"));
                encode_op(&op)
            })
            .collect(),
        other => panic!("expected op array for {what}, got {other:?}"),
    }
}

// The Rust producer's canonical op bytes for a pair.
fn produced(before: &Node, after: &Node) -> Vec<String> {
    diff(before, after).iter().map(encode_op).collect()
}

// Fold the produced diff over `before` and return the resulting canonical bytes.
fn apply_all(before: &Node, after: &Node) -> String {
    let mut tree = before.clone();
    for op in &diff(before, after) {
        tree = apply(&tree, op).expect("golden op applies").new_tree;
    }
    encode_node(&tree)
}

#[test]
fn cross_host_goldens() {
    let Some(goldens) = load() else {
        eprintln!("wire-format-fixtures corpus not found; skipping (standalone checkout)");
        return;
    };
    let entries = arr(&goldens, "goldens");
    assert!(!entries.is_empty(), "diff/goldens.json has no 'goldens'");
    for e in entries {
        let id = str_field(e, "id");
        let before = node_of(e.field("before").expect("before"), &format!("{id}.before"));
        let after = node_of(e.field("after").expect("after"), &format!("{id}.after"));
        let want = golden_op_bytes(e.field("ops").expect("ops"), &id);
        assert_eq!(produced(&before, &after), want, "diff op-script for '{id}'");
        assert_eq!(
            apply_all(&before, &after),
            encode_node(&after),
            "apply(ops, before) == after for '{id}'"
        );
    }
}

#[test]
fn cross_host_divergent() {
    let Some(goldens) = load() else {
        eprintln!("wire-format-fixtures corpus not found; skipping (standalone checkout)");
        return;
    };
    let Some(JVal::Arr(entries)) = goldens.field("divergent") else {
        eprintln!("diff/goldens.json has no 'divergent' section; skipping");
        return;
    };
    for e in entries {
        let id = str_field(e, "id");
        let before = node_of(e.field("before").expect("before"), &format!("{id}.before"));
        let after = node_of(e.field("after").expect("after"), &format!("{id}.after"));
        let hosts = e.field("hosts").expect("hosts");
        let rs_ops = hosts.field("rs").expect("rs host op-script");
        let want = golden_op_bytes(rs_ops, &id);
        assert_eq!(
            produced(&before, &after),
            want,
            "rs diff op-script for '{id}'"
        );
        assert_eq!(
            apply_all(&before, &after),
            encode_node(&after),
            "apply(ops, before) == after for '{id}'"
        );
    }
}
